# -*- coding: utf-8 -*-
"""Copy of Homework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10VBK-_CYWofyOsVuSnAcEBwfWuktHOrx

## **Homework 1**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/05/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question. Please note that your programs will be tested for other sets of inputs and outputs along with the sample provided. So test your code for other inputs.

### You can submit your solutions any number of times until the deadline.

##### Q1. Write a program that prompts the user to enter a password then prints the length of the password.

```
Enter your password: hello
Your password is 5 long.
```
"""

passWord = input("Enter your password: ")
print("Your password is", len(passWord), "long.")

"""##### Q2. Write a program that prompts the user to enter their full name then prints the number of characters in their name (do not count spaces).

```
What is your name? Amulya Katti
Amulya Katti your name has 11 characters.
```
"""

userName = input("What is your name? ")
userName = userName.replace(" ", "")
print(userName, "your name has", len(userName) , "characters.")

"""##### Q3. Write a program that prompts the user to enter a month (as a number), then prints the name of the month and the number of days in that month. Ensure that the user inputs a valid month and handle any error cases.

```
Enter the month number: 9
September has 30 days
```
"""

userMonth = input("Enter the month number: ")
while int(userMonth) not in range(1,13,1):
  print("You entered an invalid month.")
  userMonth = input("Enter the month number: ")
month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", 'November', "December"]
days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
userMonth = int(userMonth)-1
print(month[userMonth], "has", days[userMonth], "days")

"""##### Q4. Write a program that prompts the user to enter a loan amount, annual interest rate, and number of years  for a car loan. Then calculate and print the monthly payment amount.

Note:
```
PMT= [PV*i*((1+i)^n)]/[((1+i)^n)-1]
```
PMT is the monthly payment

PV is the loan amount

i is the interest rate per month in decimal form (interest rate percentage divided by 12)

n is the number of months (term of the loan in months)

```
Loan Amount: 30000.00
Annual Interest Rate: 4.00
Years: 5
Your monthly payment is: $552.50
```
"""

PV = int(input("Loan Amount: "))
annualIntRate = int(input("Annual Interest Rate: "))
years = int(input("Years: "))
annualIntRate = annualIntRate/1200
PMT = (PV*annualIntRate*((1+annualIntRate)**(years *12)))/(((1+annualIntRate)**(years*12))-1)
print("Your monthly payment is: $", round(PMT,2))

"""##### Q5. Write a program to that prompts the user to enter a string. Then check whether or not the string is a palindrome.

```
Enter a string: Madam
Madam, is a palindrome!
```
"""

userInput = input("Enter a string: ")
userList = list(userInput)
userList.reverse()
newUserInput = ''.join(userList)
if userInput.lower() == newUserInput.lower():
  print(userInput+ ", is a palindrome!")
else:
  print(userInput+ ", is not a palindrome!")

"""##### Q6. Write a program to compute and print all possible combinations of change for \$1. Denominations to be considered – quarter, dime, nickel, penny.

Hint: Use nested loops (loops within loops for the various denominations of coins)

```
Change for $1:
0 quarters, 0 dimes, 0 nickels, 100 pennies
…
4 quarters, 0 dimes, 0 nickels, 0 pennies
```
"""

print("Change for $1:")
quarters = 0
dimes = 0
nickels = 0
pennies = 100
while quarters < 4:
  while quarters == 0 and dimes < 10:
    while dimes == 0 and nickels < 20:
        while nickels == 0  and pennies <= 100:
            print(quarters, "quarters,", dimes, "dimes,", nickels, "nickels", pennies, "pennies")
            pennies += 1
        nickels += 1
        pennies = (100 - (5 * nickels))//1
        print(quarters, "quarters,", dimes, "dimes,", nickels, "nickels", pennies, "pennies")
    dimes += 1
    nickels = (100 - 10* dimes)//5
    pennies = (100 - 10* dimes - 5 * nickels)//1
    print(quarters, "quarters,", dimes, "dimes,", nickels, "nickels", pennies, "pennies")
  quarters += 1
  dimes = (100 - 25 * quarters)//10
  nickels = (100 - 25 * quarters - 10* dimes)//5
  pennies = (100 - 25 * quarters - 10* dimes - 5 * nickels)//1
  print(quarters, "quarters,", dimes, "dimes,", nickels, "nickels", pennies, "pennies")

"""##### Q7. Ask the user to enter two positive integers between 1 and 100. Read those integers. Then output a multiplication table of the first number times the second number. 

Note: You have to ensure the entered numbers are between 1 and 100 only.

```
Please enter an integer: 5
Please enter another integer: 20
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
…
5 x 20 = 100
```
"""

integerA = int(input("Please enter an integer: "))
while integerA not in range(0, 100,1):
    integerA = int(input("Please enter an integer: "))
integerB = int(input("Please enter another integer: "))
while integerB not in range(0, 100,1):
    integerB = int(input("Please enter another integer: "))
for i in range(1, integerB+1):
    result = integerA * i
    print(integerA, "*", i, "=", result)

"""##### Q8. Write a program to ask the user to enter a password. Then check to see if it is a valid password based on these requirements -

Must be at least 8 characters long

Must contain both uppercase and lowercase letters

Must contain at least one number between 0-9

Must contain a special character -!,@,#,$

If the password is not valid, ask the user to re-enter. This should continue until the user enters a valid password. After a valid password is entered, print Access Granted!

```
Please enter a password. Follow these requirements - 
a. Must be at least 8 characters long
b. Must contain both uppercase and lowercase letters
c. Must contain at least one number between 0-9
d. Must contain a special character -!,@,#,$
Password: HelloWorld1
Invalid password. Try again!
Password: Hello@World1
Access Granted!
```

"""

print("Please enter a password. Follow these requirements - ")
print("a. Must be at least 8 characters long")
print("b. Must contain both uppercase and lowercase letters")
print("c. Must contain at least one number between 0-9")
print("d. Must contain a special character -!,@,#,$")

password = input("Password: ")
states = True
conA = False
conB = False
conC = False
conD = False

while states:
    if len(password) > 8:
        conA = True
    for i in password:
        if i.isupper():
            conB = True
    for i in password:
        if i.isdigit():
            conC = True
    for i in password:
        if i in ["-", "!","@", "#", "$"]:
            conD = True

    if conA == True and conB == True and conC == True and conD == True:
        states = False
    else:
        states = True
        print("Invalid password. Try again!")
        password = input("Password: ")
print("Access Granted!")

"""##### Q9. Given the score sheet of participants in a competition, you are required to find the runner-up score. You are given scores in a list. Find the score of the runner-up.

```
list1 - [2, 3, 6, 6, 5]
runner_up - 5

list2 - [1, 7, 5, 3, 10, 4, 5, 5, 6, 11]
runner_up - 10
```
"""

import numpy as np
list1 = [2, 3, 6, 6, 5]
np1 = np.array(list1)
list2 = [1, 7, 5, 3, 10, 4, 5, 5, 6, 11]
np2 = np.array(list2)

print("list1 - ", list1)
np1 = np.unique(list1)
np1.sort()
print("runner_up - ", np1[-2])

print("list1 - ", list2)
np2 = np.unique(list2)
np2.sort()
print("runner_up - ", np2[-2])